# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-19 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161209_2227'),
        ('api', '0002_interesteduser'),
    ]

    operations = [
    ]
